module: 62-environment-ecology
level: B1
version: '2.0'
items:
- lemma: акція
  ipa: /ˈakt͡sija/
  translation: ''
  pos: noun
- lemma: альпійський
  ipa: /alʲpˈijsʲkɪj/
  translation: ''
  pos: adj
- lemma: антилопа
  ipa: /antɪlˈɔpa/
  translation: ''
  pos: noun
- lemma: асканія-нова
  ipa: /askˈanija-nɔʋa/
  translation: ''
  pos: noun
  gender: f
- lemma: багаторазовий
  ipa: /baɦatɔrazˈɔʋɪj/
  translation: ''
  pos: adj
- lemma: болото
  ipa: /bɔlˈɔtɔ/
  translation: ''
  pos: noun
  gender: n
- lemma: буковий
  ipa: /bˈukɔʋɪj/
  translation: ''
  pos: adj
- lemma: бур
  ipa: /bur/
  translation: ''
  pos: noun
  gender: m
- lemma: біологічний
  ipa: /biɔlɔɦˈit͡ʃnɪj/
  translation: ''
  pos: adj
- lemma: біорізноманіття
  ipa: /biɔriznɔmanˈittja/
  translation: ''
  pos: noun
  gender: n
- lemma: біосферний
  ipa: /biɔsfˈɛrnɪj/
  translation: ''
  pos: adj
- lemma: ведмідь
  ipa: /ʋɛdmˈidʲ/
  translation: ''
  pos: noun
  gender: m
- lemma: викид
  ipa: /ʋˈɪkɪd/
  translation: ''
  pos: noun
- lemma: вимирання
  ipa: /ʋɪmɪrˈannja/
  translation: ''
  pos: noun
  gender: n
- lemma: вирубка
  ipa: /ʋˈɪrubka/
  translation: ''
  pos: noun
  gender: f
- lemma: вирубувати
  ipa: /ʋɪrˈubuʋatɪ/
  translation: ''
  pos: verb
- lemma: вичерпний
  ipa: /ʋɪt͡ʃˈɛrpnɪj/
  translation: ''
  pos: adj
- lemma: вичерпувати
  ipa: /ʋɪt͡ʃˈɛrpuʋatɪ/
  translation: ''
  pos: verb
- lemma: вовк
  ipa: /ʋɔʋk/
  translation: ''
  pos: noun
- lemma: волокно
  ipa: /ʋɔlɔknˈɔ/
  translation: ''
  pos: noun
  gender: n
- lemma: волонтерство
  ipa: /ʋɔlɔntˈɛrstʋɔ/
  translation: ''
  pos: noun
  gender: n
- lemma: впроваджувати
  ipa: /ʋprɔʋˈadʒuʋatɪ/
  translation: ''
  pos: verb
- lemma: вугілля
  ipa: /ʋuɦˈillja/
  translation: ''
  pos: noun
  gender: n
- lemma: відновлювальний
  ipa: /ʋidnˈɔʋljuʋalʲnɪj/
  translation: ''
  pos: adj
- lemma: відновлювати
  ipa: /ʋidnˈɔʋljuʋatɪ/
  translation: ''
  pos: verb
- lemma: відходи
  ipa: /ʋidxˈɔdɪ/
  translation: ''
  pos: noun
- lemma: відчуження
  ipa: /ʋidt͡ʃˈuʒɛnnja/
  translation: ''
  pos: noun
  gender: n
- lemma: деградація
  ipa: /dɛɦradˈat͡sija/
  translation: ''
  pos: noun
  gender: f
- lemma: екосистема
  ipa: /ɛkɔsɪstˈɛma/
  translation: ''
  pos: noun
  gender: f
- lemma: електроенергія
  ipa: /ɛlɛktrɔɛnˈɛrɦija/
  translation: ''
  pos: noun
  gender: f
- lemma: електростанція
  ipa: /ɛlɛktrɔstˈant͡sija/
  translation: ''
  pos: noun
  gender: f
- lemma: забруднення
  ipa: /zabrˈudnɛnnja/
  translation: ''
  pos: noun
  gender: n
- lemma: загальніший
  ipa: /zaɦalʲniʃɪj/
  translation: ''
  pos: adj
- lemma: зазнати
  ipa: /zaznˈatɪ/
  translation: ''
  pos: verb
- lemma: заповідник
  ipa: /zapɔʋˈidnɪk/
  translation: ''
  pos: noun
- lemma: захоронення
  ipa: /zaxɔrˈɔnɛnnja/
  translation: ''
  pos: noun
  gender: n
- lemma: звалище
  ipa: /zʋˈalɪʃt͡ʃɛ/
  translation: ''
  pos: noun
  gender: n
- lemma: знищення
  ipa: /znˈɪʃt͡ʃɛnnja/
  translation: ''
  pos: noun
  gender: n
- lemma: зубр
  ipa: /zubr/
  translation: ''
  pos: noun
- lemma: компонент
  ipa: /kɔmpɔnˈɛnt/
  translation: ''
  pos: noun
- lemma: кон
  ipa: /kɔn/
  translation: ''
  pos: noun
  gender: m
- lemma: лук
  ipa: /luk/
  translation: ''
  pos: noun
- lemma: нафта
  ipa: /nˈafta/
  translation: ''
  pos: noun
  gender: f
- lemma: нелегальний
  ipa: /nɛlɛɦˈalʲnɪj/
  translation: ''
  pos: adj
- lemma: обговорюватися
  ipa: /ɔbɦɔʋˈɔrjuʋatɪsja/
  translation: ''
  pos: verb
- lemma: організм
  ipa: /ɔrɦanˈizm/
  translation: ''
  pos: noun
- lemma: охоронний
  ipa: /ɔxɔrˈɔnnɪj/
  translation: ''
  pos: adj
- lemma: охороняти
  ipa: /ɔxɔrɔnˈjatɪ/
  translation: ''
  pos: verb
- lemma: парадокс
  ipa: /paradˈɔks/
  translation: ''
  pos: noun
  gender: m
- lemma: перевищувати
  ipa: /pɛrɛʋˈɪʃt͡ʃuʋatɪ/
  translation: ''
  pos: verb
- lemma: переробка
  ipa: /pɛrɛrˈɔbka/
  translation: ''
  pos: noun
  gender: f
- lemma: планета
  ipa: /planˈɛta/
  translation: ''
  pos: noun
  gender: f
- lemma: пластика
  ipa: /plˈastɪka/
  translation: ''
  pos: noun
  gender: f
- lemma: поводження
  ipa: /pɔʋˈɔdʒɛnnja/
  translation: ''
  pos: noun
  gender: n
- lemma: поворотний
  ipa: /pɔʋɔrɔtnɪj/
  translation: ''
  pos: adj
- lemma: подільський
  ipa: /pɔdˈilʲsʲkɪj/
  translation: ''
  pos: adj
- lemma: полісся
  ipa: /pɔlˈissja/
  translation: ''
  pos: noun
  gender: n
- lemma: популяція
  ipa: /pɔpulˈjat͡sija/
  translation: ''
  pos: noun
  gender: f
- lemma: потоки
  ipa: /pɔtˈɔkɪ/
  translation: ''
  pos: noun
- lemma: потрапляти
  ipa: /pɔtraplˈjatɪ/
  translation: ''
  pos: verb
- lemma: пржевальський
  ipa: /prʒɛʋˈalʲsʲkɪj/
  translation: ''
  pos: noun
  gender: m
- lemma: прилеглий
  ipa: /prɪlˈɛɦlɪj/
  translation: ''
  pos: adj
- lemma: причорномор'я
  ipa: /prɪt͡ʃɔrnɔmɔrja/
  translation: ''
  pos: noun
  gender: n
- lemma: промисловий
  ipa: /prɔmɪslˈɔʋɪj/
  translation: ''
  pos: adj
- lemma: резерват
  ipa: /rɛzɛrʋˈat/
  translation: ''
  pos: noun
- lemma: роздільний
  ipa: /rɔzdilʲnɪj/
  translation: ''
  pos: adj
- lemma: сміття
  ipa: /smˈittja/
  translation: ''
  pos: noun
  gender: n
- lemma: спеціалізований
  ipa: /spɛt͡sializˈɔʋanɪj/
  translation: ''
  pos: adj
- lemma: старовіковий
  ipa: /starɔʋikɔʋɪj/
  translation: ''
  pos: adj
- lemma: створений
  ipa: /stʋˈɔrɛnɪj/
  translation: ''
  pos: adj
- lemma: степова
  ipa: /stɛpɔʋˈa/
  translation: ''
  pos: noun
  gender: f
- lemma: степовий
  ipa: /stɛpɔʋˈɪj/
  translation: ''
  pos: noun
- lemma: стикатися
  ipa: /stɪkˈatɪsja/
  translation: ''
  pos: verb
- lemma: страус
  ipa: /strˈaus/
  translation: ''
  pos: noun
- lemma: стійкий
  ipa: /stijkˈɪj/
  translation: ''
  pos: adj
- lemma: сухіше
  ipa: /suxˈiʃɛ/
  translation: ''
  pos: adv
- lemma: сільськогосподарський
  ipa: /silʲsʲkɔɦɔspɔdˈarsʲkɪj/
  translation: ''
  pos: adj
- lemma: тканинний
  ipa: /tkanˈɪnnɪj/
  translation: ''
  pos: adj
- lemma: товтри
  ipa: /tˈɔʋtrɪ/
  translation: ''
  pos: noun
- lemma: тонна
  ipa: /tˈɔnna/
  translation: ''
  pos: noun
- lemma: урядовий
  ipa: /urjadˈɔʋɪj/
  translation: ''
  pos: adj
- lemma: утилізація
  ipa: /utɪlizˈat͡sija/
  translation: ''
  pos: noun
  gender: f
- lemma: утилізувати
  ipa: /utɪlizuʋˈatɪ/
  translation: ''
  pos: verb
- lemma: чорнобиль
  ipa: /t͡ʃɔrnˈɔbɪlʲ/
  translation: ''
  pos: noun
  gender: m
- lemma: чорнобильський
  ipa: /t͡ʃɔrnˈɔbɪlʲsʲkɪj/
  translation: ''
  pos: adj
- lemma: чорнозем
  ipa: /t͡ʃɔrnˈɔzɛm/
  translation: ''
  pos: noun
- lemma: юнеско
  ipa: /junɛskɔ/
  translation: ''
  pos: noun
  gender: n
- lemma: ґрунт
  ipa: /grunt/
  translation: ''
  pos: noun
