module: 62-environment-ecology
level: B1
version: '2.0'
items:
- lemma: акція
  ipa: /ˈakt͡sija/
  translation: action, promotion, share
  pos: noun
- lemma: альпійський
  ipa: /alʲpˈijsʲkɪj/
  translation: Alpine
  pos: adj
- lemma: антилопа
  ipa: /antɪlˈɔpa/
  translation: antelope
  pos: noun
- lemma: асканія-нова
  ipa: /askˈanija-nɔʋa/
  translation: Askania-Nova
  pos: noun
  gender: f
- lemma: багаторазовий
  ipa: /baɦatɔrazˈɔʋɪj/
  translation: multiple-use, reusable
  pos: adj
- lemma: болото
  ipa: /bɔlˈɔtɔ/
  translation: swamp, marsh
  pos: noun
  gender: n
- lemma: буковий
  ipa: /bˈukɔʋɪj/
  translation: beech (adj)
  pos: adj
- lemma: бур
  ipa: /bur/
  translation: drill
  pos: noun
  gender: m
- lemma: біологічний
  ipa: /biɔlɔɦˈit͡ʃnɪj/
  translation: biological
  pos: adj
- lemma: біосферний
  ipa: /biɔsfˈɛrnɪj/
  translation: biospheric
  pos: adj
- lemma: ведмідь
  ipa: /ʋɛdmˈidʲ/
  translation: bear
  pos: noun
  gender: m
- lemma: викид
  ipa: /ʋˈɪkɪd/
  translation: emission, discharge
  pos: noun
- lemma: вимирання
  ipa: /ʋɪmɪrˈannja/
  translation: extinction
  pos: noun
  gender: n
- lemma: вирубка
  ipa: /ʋˈɪrubka/
  translation: felling, cutting down
  pos: noun
  gender: f
- lemma: вирубувати
  ipa: /ʋɪrˈubuʋatɪ/
  translation: to cut down
  pos: verb
- lemma: вичерпний
  ipa: /ʋɪt͡ʃˈɛrpnɪj/
  translation: comprehensive, exhaustive
  pos: adj
- lemma: вичерпувати
  ipa: /ʋɪt͡ʃˈɛrpuʋatɪ/
  translation: to exhaust, to deplete
  pos: verb
- lemma: волокно
  ipa: /ʋɔlɔknˈɔ/
  translation: fiber
  pos: noun
  gender: n
- lemma: волонтерство
  ipa: /ʋɔlɔntˈɛrstʋɔ/
  translation: volunteering
  pos: noun
  gender: n
- lemma: впроваджувати
  ipa: /ʋprɔʋˈadʒuʋatɪ/
  translation: to implement
  pos: verb
- lemma: вугілля
  ipa: /ʋuɦˈillja/
  translation: coal
  pos: noun
  gender: n
- lemma: відновлювати
  ipa: /ʋidnˈɔʋljuʋatɪ/
  translation: to restore (imperfective)
  pos: verb
- lemma: відходи
  ipa: /ʋidxˈɔdɪ/
  translation: waste, scrap
  pos: noun
- lemma: відчуження
  ipa: /ʋidt͡ʃˈuʒɛnnja/
  translation: alienation
  pos: noun
  gender: n
- lemma: деградація
  ipa: /dɛɦradˈat͡sija/
  translation: degradation
  pos: noun
  gender: f
- lemma: екосистема
  ipa: /ɛkɔsɪstˈɛma/
  translation: ecosystem
  pos: noun
  gender: f
- lemma: електроенергія
  ipa: /ɛlɛktrɔɛnˈɛrɦija/
  translation: electricity
  pos: noun
  gender: f
- lemma: електростанція
  ipa: /ɛlɛktrɔstˈant͡sija/
  translation: power station
  pos: noun
  gender: f
- lemma: забруднення
  ipa: /zabrˈudnɛnnja/
  translation: pollution, contamination
  pos: noun
  gender: n
- lemma: загальніший
  ipa: /zaɦalʲniʃɪj/
  translation: more general
  pos: adj
- lemma: зазнати
  ipa: /zaznˈatɪ/
  translation: to undergo, to suffer (perfective)
  pos: verb
- lemma: заповідник
  ipa: /zapɔʋˈidnɪk/
  translation: nature reserve
  pos: noun
- lemma: захоронення
  ipa: /zaxɔrˈɔnɛnnja/
  translation: burial, cemetery
  pos: noun
  gender: n
- lemma: звалище
  ipa: /zʋˈalɪʃt͡ʃɛ/
  translation: dump, landfill
  pos: noun
  gender: n
- lemma: знищення
  ipa: /znˈɪʃt͡ʃɛnnja/
  translation: destruction
  pos: noun
  gender: n
- lemma: зубр
  ipa: /zubr/
  translation: bison
  pos: noun
- lemma: компонент
  ipa: /kɔmpɔnˈɛnt/
  translation: component
  pos: noun
- lemma: кон
  ipa: /kɔn/
  translation: ''
  pos: noun
  gender: m
- lemma: лук
  ipa: /luk/
  translation: bow (weapon), onion (archaic)
  pos: noun
- lemma: нафта
  ipa: /nˈafta/
  translation: oil, petroleum
  pos: noun
  gender: f
- lemma: нелегальний
  ipa: /nɛlɛɦˈalʲnɪj/
  translation: illegal
  pos: adj
- lemma: обговорюватися
  ipa: /ɔbɦɔʋˈɔrjuʋatɪsja/
  translation: to be discussed
  pos: verb
- lemma: олень
  ipa: /ˈɔlɛnʲ/
  translation: deer
  pos: noun
  gender: m
- lemma: організм
  ipa: /ɔrɦanˈizm/
  translation: organism
  pos: noun
- lemma: охоронний
  ipa: /ɔxɔrˈɔnnɪj/
  translation: security (adj), protective
  pos: adj
- lemma: охороняти
  ipa: /ɔxɔrɔnˈjatɪ/
  translation: to guard, to protect
  pos: verb
- lemma: парадокс
  ipa: /paradˈɔks/
  translation: paradox
  pos: noun
  gender: m
- lemma: перевищувати
  ipa: /pɛrɛʋˈɪʃt͡ʃuʋatɪ/
  translation: to exceed
  pos: verb
- lemma: переробка
  ipa: /pɛrɛrˈɔbka/
  translation: reworking, recycling
  pos: noun
  gender: f
- lemma: планета
  ipa: /planˈɛta/
  translation: planet
  pos: noun
  gender: f
- lemma: пластика
  ipa: /plˈastɪka/
  translation: plastic
  pos: noun
  gender: f
- lemma: поводження
  ipa: /pɔʋˈɔdʒɛnnja/
  translation: treatment, behavior, handling
  pos: noun
  gender: n
- lemma: поворотний
  ipa: /pɔʋɔrɔtnɪj/
  translation: turn (adj), pivotal
  pos: adj
- lemma: подільський
  ipa: /pɔdˈilʲsʲkɪj/
  translation: Podillian (adj)
  pos: adj
- lemma: полісся
  ipa: /pɔlˈissja/
  translation: Polissia (region)
  pos: noun
  gender: n
- lemma: популяція
  ipa: /pɔpulˈjat͡sija/
  translation: population (biological)
  pos: noun
  gender: f
- lemma: потоки
  ipa: /pɔtˈɔkɪ/
  translation: streams, flows
  pos: noun
- lemma: потрапляти
  ipa: /pɔtraplˈjatɪ/
  translation: to get to (imperfective)
  pos: verb
- lemma: пржевальський
  ipa: /prʒɛʋˈalʲsʲkɪj/
  translation: Przewalski (name)
  pos: noun
  gender: m
- lemma: прилеглий
  ipa: /prɪlˈɛɦlɪj/
  translation: adjacent, adjoining
  pos: adj
- lemma: причорномор'я
  ipa: /prɪt͡ʃɔrnɔmɔrja/
  translation: Black Sea region
  pos: noun
  gender: n
- lemma: промисловий
  ipa: /prɔmɪslˈɔʋɪj/
  translation: industrial
  pos: adj
- lemma: резерват
  ipa: /rɛzɛrʋˈat/
  translation: reservation, preserve
  pos: noun
- lemma: роздільний
  ipa: /rɔzdilʲnɪj/
  translation: separate, disjoint
  pos: adj
- lemma: сміття
  ipa: /smˈittja/
  translation: trash, garbage
  pos: noun
  gender: n
- lemma: старовіковий
  ipa: /starɔʋikɔʋɪj/
  translation: centuries-old
  pos: adj
- lemma: створений
  ipa: /stʋˈɔrɛnɪj/
  translation: created
  pos: adj
- lemma: степова
  ipa: /stɛpɔʋˈa/
  translation: steppe (adj female)
  pos: noun
  gender: f
- lemma: степовий
  ipa: /stɛpɔʋˈɪj/
  translation: steppe (adj)
  pos: noun
- lemma: стикатися
  ipa: /stɪkˈatɪsja/
  translation: to encounter, to face
  pos: verb
- lemma: страус
  ipa: /strˈaus/
  translation: ostrich
  pos: noun
- lemma: стійкий
  ipa: /stijkˈɪj/
  translation: stable, resistant, resilient
  pos: adj
- lemma: сухіше
  ipa: /suxˈiʃɛ/
  translation: drier
  pos: adv
- lemma: тканинний
  ipa: /tkanˈɪnnɪj/
  translation: fabric (adj)
  pos: adj
- lemma: товтри
  ipa: /tˈɔʋtrɪ/
  translation: Tovtry (geological hills)
  pos: noun
- lemma: тонна
  ipa: /tˈɔnna/
  translation: ton
  pos: noun
- lemma: урядовий
  ipa: /urjadˈɔʋɪj/
  translation: governmental
  pos: adj
- lemma: утилізація
  ipa: /utɪlizˈat͡sija/
  translation: utilization, recycling
  pos: noun
  gender: f
- lemma: утилізувати
  ipa: /utɪlizuʋˈatɪ/
  translation: to utilize, to recycle
  pos: verb
- lemma: чорнобиль
  ipa: /t͡ʃɔrnˈɔbɪlʲ/
  translation: Chornobyl
  pos: noun
  gender: m
- lemma: чорнобильський
  ipa: /t͡ʃɔrnˈɔbɪlʲsʲkɪj/
  translation: Chornobyl (adj)
  pos: adj
- lemma: чорнозем
  ipa: /t͡ʃɔrnˈɔzɛm/
  translation: chernozem (soil)
  pos: noun
- lemma: юнеско
  ipa: /junɛskɔ/
  translation: UNESCO
  pos: noun
  gender: n
- lemma: ґрунт
  ipa: /grunt/
  translation: soil, ground, foundation
  pos: noun
